[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gasopt"
version = "0.1.0"
description = "Otimização de refratometria de gases"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pandas",
    "emcee",
    "kneed"
]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["tests*", "notebooks*"]
